### ISSUE TITLE
immortalwrt版本的机型型号不对

### ISSUE THREAD

**Issue by ChinaZWY** [weigefenxiang/360T7#1]
![2023-07-09_210718](https://github.com/weigefenxiang/360T7/assets/6417571/fe556307-7a30-4ff5-b9c3-e15158f3ce57)
下载后打开发现里头是别的机型型号，还有天灵大佬在前段时间应该在
https://github.com/immortalwrt/immortalwrt/commit/91ad7175913150aab3fb20eb02a46e20c43b15c3
开启了WED加速，就等大佬你云编译的immortalwrt刷入测试效果了

**Comment by weigefenxiang** [comment]
更新了，名字改了
